### ISSUE TITLE
如何直接克隆别人的docker？

### ISSUE THREAD

**Issue by vm669** [jklolixxs/Docker_Image_Builder#1]
如果我就要目前用的别人的镜像，只是需要换一个用户名和网址，不想都一样，如何直接克隆别人的docker到一个新的存放地址呢？

**Comment by jklolixxs** [comment]
据我所知，应该是做不到，唯一的办法就是拿到对方的Dockerfile，重新构建Docker镜像，并发布到不一样的Docker Hub仓库
